### ISSUE TITLE
Confirmation on the sign for value of Transactions Analyzer

### ISSUE THREAD

**Issue by viper7882** [backtrader2/backtrader#82]
Hi @neilsmurphy,

Looking into this particular line in Transactions Analyzer:https://github.com/backtrader2/backtrader/blob/master/backtrader/analyzers/transactions.py#L98, it seems like the value is calculated using the following formula:
```python
-size * price
```
The result is that for long order with positive size, the value will always be negative.

In contradictory, common understanding of value should be:
```python
abs(size) * price
```
i.e. the size is always positive when calculating value.

Mind to comment?

**Comment by neilsmurphy** [comment]
I believe in selling situations, units are negative. Hence changing the sign to get positive values. 
```
# Running a backtest.
# Here's a buy
2016-02-24, BUY EXECUTED for FB, Price: 104.21, Cost: 1042.10, Comm: 0.00, Size:   10.0000, 
[10, 104.21, 0, 'FB', -1042.1]

# Here's a sale. 
2016-03-02, SELL EXECUTED for FB, Price: 109.68, Cost: 1078.30, Comm: 0.00, Size:  -10.0000, 
2016-03-02, FB Closed: PnL Gross 18.5, Net 18.5,
[-10, 109.68, 0, 'FB', 1096.8]
```
We can see the cash adjust in the correct direction, negative cash for a buy, positive cash for a sale.

**Comment by viper7882** [comment]
Thanks @neilsmurphy for looking into this matter for us.

We believe the confusion comes due to the title **value**. In this case the value entitled @ https://github.com/backtrader2/backtrader/blob/master/backtrader/analyzers/transactions.py#L62 should be changed from **value** to **cash_flow**. Value should be always having positive sign. Cash flow can have both positive and negative sign.

Any other thoughts?

**Comment by neilsmurphy** [comment]
Hey @viper7882 . The original set up of this analyzer was dictated by `pyfolio` and the terms were taken from there. I do not know why. The issue here is that we are not actively developing backtrader. Backtrader2 was put in place to allow for bug fixes and updates to keep it working properly. The original code is essentially stale as the original developer has left the project and only he can update the original codebase. 

This fix you propose would require us to update the docs, which we also do not have access to. And given the fact this can easily be modified on your end as analyzers are reasonably easy to update, I'm going to suggest we pass on this issue. 

Thanks for bringing this up.

**Comment by viper7882** [comment]
Roger that @neilsmurphy. Thanks again for providing more background.

We have no issue fixing it on our end.
